/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package axion2014;

import java.awt.PopupMenu;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thusitha
 */
public class PPList extends javax.swing.JFrame {
    PutInTableFromDB pitf1 = new PutInTableFromDB();
    PutInTable pit1 = new PutInTable();
    /**
     * Creates new form Calculator
     */
    public PPList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(214, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(214, 600));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "CUSTOMER", "SUPPLIER", "EMPLOYEE", "BONDS", "OTHER" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        jTable11.setAutoCreateRowSorter(true);
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "NAME"
            }
        ));
        jScrollPane1.setViewportView(jTable11);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 440));

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 90, -1));

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 90, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoard.removeSelected();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pit1.removeAllFromTable(jTable11);
        if(jComboBox3.getSelectedIndex()==0){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT DISTINCT* FROM CUSTOMER,SUPPLIER,EMPLOYEE,BONDS,OTHER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==1){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM CUSTOMER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==2){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM SUPPLIER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==3){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM EMPLOYEE");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==4){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM BONDS");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==5){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM OTHER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        pit1.removeAllFromTable(jTable11);
        if(jComboBox3.getSelectedIndex()==0){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT DISTINCT * FROM CUSTOMER,SUPPLIER,EMPLOYEE,BONDS,OTHER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==1){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM CUSTOMER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==2){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM SUPPLIER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==3){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM EMPLOYEE");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==4){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM BONDS");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }else if(jComboBox3.getSelectedIndex()==5){
            try {
                pitf1.putTableFromDB(jTable11, "SELECT * FROM OTHER");
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable11;
    // End of variables declaration//GEN-END:variables
}
